# Example of the configuration of the workflow engine as a Fission Environment\n\n/
# Source: fission-workflows/templates/deployment.yaml
# Workflow Apiserver is an optional component that allows users to query the workflows API through the Fission apiserver.

# Workflow Engine is deployed as just another Fission environment.
apiVersion: fission.io/v1
kind: Environment
metadata:
  name: workflows-env
  namespace: default
spec:
  version: 2
  TerminationGracePeriod: 5
  runtime:
    image: "fission/workflow-env:0.5.0"
    container:
      command: ["/fission-workflows-bundle"]
      env:
      - name: ES_NATS_URL
        value: "nats://defaultFissionAuthToken@nats-streaming.fission:4222"
      - name: ES_NATS_CLUSTER
        value: "fissionMQTrigger"
      - name: FNENV_FISSION_CONTROLLER
        value: "http://controller.fission"
      - name: FNENV_FISSION_EXECUTOR
        value: "http://executor.fission"
  builder:
    image: "fission/workflow-build-env:0.5.0"
    command: "defaultBuild"
  allowedFunctionsPerContainer: infinite

